name: portfolio
description: "Portfolio Site"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  mailto: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: paperlogy
      fonts:
        - asset: assets/fonts/PaperLogy/Paperlogy-1Thin.ttf
          weight: 100
        - asset: assets/fonts/PaperLogy/Paperlogy-2ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PaperLogy/Paperlogy-3Light.ttf
          weight: 300
        - asset: assets/fonts/PaperLogy/Paperlogy-4Regular.ttf
          weight: 400
        - asset: assets/fonts/PaperLogy/Paperlogy-5Medium.ttf
          weight: 500
        - asset: assets/fonts/PaperLogy/Paperlogy-6SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PaperLogy/Paperlogy-7Bold.ttf
          weight: 700
        - asset: assets/fonts/PaperLogy/Paperlogy-8ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PaperLogy/Paperlogy-9Black.ttf
          weight: 900
